name: Code Quality

on:
  push:
    paths:
      - "**.py"

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run black
        uses: piotrpawlaczek/python-blacken@release/stable
        with:
          line-length: '120'
          path: '.'
          sanity-check: 'safe'
          only-check: 'no'
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: "./"
          plugins: flake8-bugbear pep8-naming flake8-commas flake8-use-fstring
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}