name: Perl Lint

on:
  push:
    paths:
      - "**.pl"

jobs:
  perl_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl 
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure Task::PerlCriticAllPolicies
      - name: Run perlcritic
        run: perlcritic . --verbose 11
        